GRLIB = C:/Users/Admin/Downloads/Programs/ReadyLib/dev
GSRC = ..\code\GProject\src
GBIN = bin
GBUILD = build
GTARGET = $(GBIN)\gp_c.exe

GINCS = \
    -I$(GSRC)\include \
    -I$(GRLIB)/gtk/3.6.4/mingw32/include/gtk-3.0 -I$(GRLIB)/gtk/3.6.4/mingw32/include/cairo -I$(GRLIB)/gtk/3.6.4/mingw32/include/pango-1.0 -I$(GRLIB)/gtk/3.6.4/mingw32/include/atk-1.0 -I$(GRLIB)/gtk/3.6.4/mingw32/include/cairo -I$(GRLIB)/gtk/3.6.4/mingw32/include/pixman-1 -I$(GRLIB)/gtk/3.6.4/mingw32/include -I$(GRLIB)/gtk/3.6.4/mingw32/include/freetype2 -I$(GRLIB)/gtk/3.6.4/mingw32/include -I$(GRLIB)/gtk/3.6.4/mingw32/include/libpng15 -I$(GRLIB)/gtk/3.6.4/mingw32/include/gdk-pixbuf-2.0 -I$(GRLIB)/gtk/3.6.4/mingw32/include/libpng15 -I$(GRLIB)/gtk/3.6.4/mingw32/include/glib-2.0 -I$(GRLIB)/gtk/3.6.4/mingw32/lib/glib-2.0/include \
    
GLIBS = \
    -L$(GRLIB)/gtk/3.6.4/mingw32/lib \
    -lgtk-3 -lgdk-3 -lgdi32 -limm32 -lshell32 -lole32 -Wl,-luuid -lpangocairo-1.0 -lpangoft2-1.0 -lfreetype -lfontconfig -lpangowin32-1.0 -lgdi32 -lpango-1.0 -lm -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 \
    
GOBJS = \
    $(patsubst $(GSRC)/%.c, $(GBUILD)/%.o, $(wildcard $(GSRC)/*.c)) \
    $(patsubst $(GSRC)/manager/%.c, $(GBUILD)/%.o, $(wildcard $(GSRC)/manager/*.c)) \

GCFLAGS = \
    -std=gnu11 \
    -mms-bitfields \
    
all: clean compile run

compile: $(GOBJS)
	@if not exist $(GBIN) ( mkdir $(GBIN) )
	gcc $(GCFLAGS) -o $(GTARGET) $(GOBJS) $(GLIBS) 
$(GBUILD)/%.o: $(GSRC)/%.c
	@if not exist $(GBUILD) ( mkdir $(GBUILD) )
	gcc $(GCFLAGS) -c $< -o $@ $(GINCS)
$(GBUILD)/%.o: $(GSRC)/manager/%.c
	@if not exist $(GBUILD) ( mkdir $(GBUILD) )
	gcc $(GCFLAGS) -c $< -o $@ $(GINCS)
run:
	@run
clean: 
	del /q $(GBUILD)\*.* $(GTARGET)
