GBIN = bin
GBUILD = build
GTARGET = $(GBIN)\gp_c_qt.exe

all: clean_exe qmake compile run

qmake:
	@qmake
compile:
	@mingw32-make
run:
	@$(GTARGET)
clean_exe: 
	del /q $(GTARGET)
clean: 
	@mingw32-make clean
	del /q $(GBUILD)\* $(GBIN)\*
